//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRS.ReportApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDb)\v11.0;AttachDbFilename=C:\Users\Max\Documents\GIT-REPOS\PUCMM\BusReservationSys\src\BRS\BRS.WebUI\App_Data\BRSDB.mdf;Initial Catalog=BRS.Data.EF_Context.DBContext;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string BRSDBConnectionString {
            get {
                return ((string)(this["BRSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Max\\Documents\\GIT-RE" +
            "POS\\PUCMM\\BusReservationSys\\src\\BRS\\BRS.DesktopUI\\aspnet-BRS.WebUI-2015111606062" +
            "6.mdf;Initial Catalog=aspnet-BRS.WebUI-20151116060626;Integrated Security=True")]
        public string aspnet_BRS_WebUI_20151116060626ConnectionString {
            get {
                return ((string)(this["aspnet_BRS_WebUI_20151116060626ConnectionString"]));
            }
        }
    }
}
